In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

C:\Users\admin\AppData\Local\Temp\ipykernel_13092\1801383384.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
dataset=pd.read_excel('Data_Train.xlsx')

In [3]:
dataset.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [4]:
dataset.drop(['Date_of_Journey', 'Dep_Time', 'Arrival_Time', 'Duration'], axis=1, inplace=True)

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset = dataset.astype(int)

In [7]:
dataset

,Price,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Total_Stops_non-stop,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,3897,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
1,7662,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,13882,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,6218,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,13302,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,4107,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10679,4145,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10680,7229,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10681,12648,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10682,11753,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [8]:
x=dataset.drop('Price',axis=1)

In [9]:
x.columns

Index(['Airline_Air India', 'Airline_GoAir', 'Airline_IndiGo',
       'Airline_Jet Airways', 'Airline_Jet Airways Business',
       'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara',
       ...
       'Total_Stops_non-stop', 'Additional_Info_1 Short layover',
       'Additional_Info_2 Long layover', 'Additional_Info_Business class',
       'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype='object', length=160)

In [10]:
y=dataset[["Price"]]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [12]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=50,random_state=0)
regressor.fit(x_train,y_train)

E:\software installtalation paths\anaconda\envs\time\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(n_estimators=50, random_state=0)

In [13]:
y_pred=regressor.predict(x_test)

In [14]:
from sklearn.metrics import r2_score

In [15]:
r_score=r2_score(y_test,y_pred)
r_score

0.7522896101156623

In [16]:
import pickle

In [17]:
filename='ticket_pred.sav'

In [18]:
pickle.dump(regressor,open(filename,'wb'))

In [19]:
testdata=pd.read_excel("Test_set.xlsx")

In [20]:
testdata.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [21]:
testdata.drop(['Date_of_Journey', 'Dep_Time', 'Arrival_Time', 'Duration'], axis=1, inplace=True)

In [ ]:
for a in x.columns:
    if a not in testdata1.columns:
        testdata1[a] = False

In [22]:
testdata=pd.get_dummies(testdata,drop_first=True)

In [23]:
testdata=dataset.astype(int)

In [24]:
testdata.columns

Index(['Price', 'Airline_Air India', 'Airline_GoAir', 'Airline_IndiGo',
       'Airline_Jet Airways', 'Airline_Jet Airways Business',
       'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet',
       ...
       'Total_Stops_non-stop', 'Additional_Info_1 Short layover',
       'Additional_Info_2 Long layover', 'Additional_Info_Business class',
       'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype='object', length=161)

In [25]:
loaded_model=pickle.load(open('ticket_pred.sav','rb'))

In [26]:
result=loaded_model.predict(testdata)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Price

In [ ]:
testdata1['predictions'] = result